group=me.samsuik.sakura
version=26.2
mcVersion=26.2
apiVersion=26.2

paperRef=c9e894d3cc03f21f80de4f4061a795e11941e89a
#paper.runWorkDir=../26.2.x-dev

org.gradle.jvmargs=-Xmx2G
org.gradle.vfs.watch=false
org.gradle.caching=true
org.gradle.parallel=true
# org.gradle.daemon=true
# org.gradle.configureondemand=true