group=me.samsuik.sakura
version=26.2
mcVersion=26.2
apiVersion=26.2

paperRef=bb32c3767ed5acb7583a324bce51692b55ff4079
#paper.runWorkDir=../26.1.x-dev

org.gradle.jvmargs=-Xmx2G
org.gradle.vfs.watch=false
org.gradle.caching=true
org.gradle.parallel=true
# org.gradle.daemon=true
# org.gradle.configureondemand=true