group=me.samsuik.sakura
mcVersion=26.3
apiVersion=26.3
paperRef=abfdaed87a695450cdaa5711ec52833b3ce8997d
#paper.runWorkDir=../26.3.x-dev

org.gradle.jvmargs=-Xmx2G
org.gradle.vfs.watch=false
org.gradle.caching=true
org.gradle.parallel=true
# org.gradle.daemon=true
# org.gradle.configureondemand=true